/*
 * Ultima IV - Quest Of The Avatar
 * (c) Copyright 1987 Lord British
 */

#ifndef __I18N_EN_H__
#define __I18N_EN_H__

/* TITLE_0.C */
#define U4TEXT_TITLE_0_297 "In another world, in a time to come."
#define U4TEXT_TITLE_0_298 "Options:"
#define U4TEXT_TITLE_0_299 "Return to the view"
#define U4TEXT_TITLE_0_300 "Journey Onward"
#define U4TEXT_TITLE_0_301 "Initiate New Game"
#define U4TEXT_TITLE_0_302 "Conversion by James Van Artsdalen"
#define U4TEXT_TITLE_0_303 "\x9 Copyright 1987 Lord British"

/* TITLE_1.C */
#define U4TEXT_TITLE_1_TEXT_1 \
"Entrusted to deliver an uncounted purse\n\
of gold, thou dost meet a poor beggar.\n\
Dost thou A) deliver the gold knowing\n\
the Trust in thee was well placed, or\n\
B) show Compassion, giving the beggar a\n\
coin, knowing it won't be missed?"

#define U4TEXT_TITLE_1_TEXT_2 \
"Thou has been prohibited by thy absent\n\
Lord from joining thy friends in a close\n\
pitched battle. Dost thou A) refrain, so\n\
thou may Honesty claim obedience, or\n\
B) show Valor, and aid thy comrades,\n\
knowing thou may deny it later?"

#define U4TEXT_TITLE_1_TEXT_3 \
"A merchant owes thy friend money, now\n\
long past due.  Thou dost see the same\n\
merchant drop a purse of gold. Dost thou\n\
A) Honestly return the purse intact, or\n\
B) Justly give thy friend a portion of\n\
the gold first?"

#define U4TEXT_TITLE_1_TEXT_4 \
"Thee and thy friend are valiant but\n\
penniless warriors.  Thou both go out to\n\
slay a mighty dragon.  Thy friend thinks\n\
he slew it; thee did.  When asked, dost\n\
thou A) Truthfully claim the gold, or\n\
B) Allow thy friend the large reward?"

#define U4TEXT_TITLE_1_TEXT_5 \
"Thou art sworn to protect thy Lord at\n\
any cost, yet thou know he hath\n\
committed a crime.  Authorities ask thee\n\
of the affair.  Dost thou A) break thine\n\
oath by Honestly speaking, or B) uphold\n\
Honor by silently keeping thine oath?"

#define U4TEXT_TITLE_1_TEXT_6 \
"Thy friend seeks admittance to thy\n\
Spiritual order. Thou art asked to vouch\n\
for his purity of Spirit, of which thou\n\
art unsure.  Dost thou A) Honestly\n\
express thy doubt, or B) Vouch for him\n\
hoping for his Spiritual improvement?"

#define U4TEXT_TITLE_1_TEXT_7 \
"Thy Lord mistakenly believes he slew a\n\
dragon.  Thou hast proof that thy lance\n\
felled the beast.  When asked, dost thou\n\
A) Honestly claim the kill and the\n\
prize, or B) Humbly permit thy Lord his\n\
belief?"

#define U4TEXT_TITLE_1_TEXT_8 \
"Thou dost manage to disarm thy mortal\n\
enemy in a duel.  He is at thy mercy.\n\
Dost thou A) show Compassion by\n\
permitting him to yield, or B) slay him\n\
as expected of a Valiant duelist?"

#define U4TEXT_TITLE_1_TEXT_9 \
"After 20 years thou hast found the\n\
slayer of thy best friends.  The villain\n\
proves to be a man who provides the sole\n\
support for a young girl.  Dost thou\n\
A) spare him in Compassion for the girl,\n\
or B) slay him in the name of Justice?"

#define U4TEXT_TITLE_1_TEXT_10 \
"Thee and thy friends have been routed\n\
and ordered to retreat.  In defiance of\n\
thy orders, dost thou A) stop in\n\
Compassion to aid a wounded companion,\n\
or B) Sacrifice thyself to slow the\n\
pursuing enemy, so others may escape?"

#define U4TEXT_TITLE_1_TEXT_11 \
"Thou art sworn to uphold a Lord who\n\
participates in the forbidden torture of\n\
prisoners.  Each night their cries of\n\
pain reach thee.  Dost thou A) show\n\
Compassion by reporting the deeds, or\n\
B) Honor thy oath and ignore the deeds?"

#define U4TEXT_TITLE_1_TEXT_12 \
"Thou hast been taught to preserve all\n\
life as sacred. A man lies fatally stung\n\
by a venomous serpent.  He pleads for a\n\
merciful death.  Dost thou A) show\n\
Compassion and end his pain, or B) heed\n\
thy Spiritual beliefs and refuse?"

#define U4TEXT_TITLE_1_TEXT_13 \
"As one of the King's Guard, thy Captain\n\
has asked that one amongst you visit\n\
a hospital to cheer the children with\n\
tales of thy valiant deeds.  Dost thou\n\
A) Show thy Compassion and play the\n\
braggart, or B) Humbly let another go?"

#define U4TEXT_TITLE_1_TEXT_14 \
"Thou hast been sent to secure a needed\n\
treaty with a distant Lord.  Thy host is\n\
agreeable to the proposal but insults\n\
thy country at dinner.  Dost thou\n\
A) Valiantly bear the slurs, or\n\
B) Justly rise and demand an apology?"

#define U4TEXT_TITLE_1_TEXT_15 \
"A mighty knight accosts thee and demands\n\
thy food.  Dost thou A) Valiantly refuse\n\
and engage the knight, or B) Sacrifice\n\
thy food unto the hungry knight?"

#define U4TEXT_TITLE_1_TEXT_16 \
"During battle thou art ordered to guard\n\
thy commander's empty tent.  The battle\n\
goes poorly and thou dost yearn to aid\n\
thy fellows.  Dost thou A) Valiantly\n\
enter the battle to aid thy companions,\n\
or B) Honor thy post as guard?"

#define U4TEXT_TITLE_1_TEXT_17 \
"A local bully pushes for a fight.  Dost\n\
thou A) Valiantly trounce the rogue, or\n\
B) Decline, knowing in thy Spirit that\n\
no lasting good will come of it?"

#define U4TEXT_TITLE_1_TEXT_18 \
"Although a teacher of music, thou art\n\
a skillful wrestler.  Thou hast been\n\
asked to fight in a local championship.\n\
Dost thou A) accept the invitation and\n\
Valiantly fight to win, or B) Humbly\n\
decline knowing thou art sure to win?"

#define U4TEXT_TITLE_1_TEXT_19 \
"During a pitched battle, thou dost see\n\
a fellow desert his post, endangering\n\
many.  As he flees, he is set upon by\n\
several enemies. Dost thou A) Justly let\n\
him fight alone, or B) Risk Sacrificing\n\
thine own life to aid him?"

#define U4TEXT_TITLE_1_TEXT_20 \
"Thou hast sworn to do thy Lord's\n\
bidding in all.  He covets a piece of\n\
land and orders the owner removed.  Dost\n\
thou A) serve Justice refusing to act,\n\
thus being disgraced, or B) Honor thine\n\
oath and unfairly evict the landowner?"

#define U4TEXT_TITLE_1_TEXT_21 \
"Thou dost believe that virtue resides\n\
in all people.  Thou dost see a rogue\n\
steal from thy Lord.  Dost thou A) call\n\
him to Justice, or B) personally try to\n\
sway him back to the Spiritual path of\n\
good?"

#define U4TEXT_TITLE_1_TEXT_22 \
"Unwitnessed, thou hast slain a great\n\
dragon in self defense.  A poor warrior\n\
claims the offered reward.  Dost thou\n\
A) Justly step forward to claim the\n\
reward, or B) Humbly go about life,\n\
secure in thy self esteem?"

#define U4TEXT_TITLE_1_TEXT_23 \
"Thou art a bounty hunter sworn to return\n\
an alleged murder.  After his capture\n\
thou believest him to be innocent.  Dost\n\
thou A) Sacrifice thy sizable bounty\n\
for thy belief, or B) Honor thy oath to\n\
return him as thou hast promised?"

#define U4TEXT_TITLE_1_TEXT_24 \
"Thou hast spent thy life in charitable\n\
and righteous work.  Thine uncle the\n\
innkeeper lies ill and asks you to take\n\
over his tavern.  Dost thou A) Sacrifice\n\
thy life of purity to aid thy kin, or\n\
B) decline & follow thy Spirit's call?"

#define U4TEXT_TITLE_1_TEXT_25 \
"Thou art an elderly, wealthy eccentric.\n\
Thy end is near. Dost thou A) donate all\n\
thy wealth to feed hundreds of starving\n\
children, and receive public adulation,\n\
or B) Humbly live out thy life, willing\n\
thy fortune to thy heirs?"

#define U4TEXT_TITLE_1_TEXT_26 \
"In thy youth thou pledged to marry thy\n\
sweetheart.  Now thou art on a sacred\n\
quest in distant lands.  Thy sweetheart\n\
asks thee to keep thy vow.  Dost thou\n\
A) Honor thy pledge to wed, or B) follow\n\
thy Spiritual crusade?"

#define U4TEXT_TITLE_1_TEXT_27 \
"Thou art at a crossroads in thy life.\n\
Dost thou A) Choose the Honorable life\n\
of a Paladin, striving for Truth and\n\
Courage, or B) Choose the Humble life\n\
of a Shepherd, and a world of simplicity\n\
and peace?"

#define U4TEXT_TITLE_1_TEXT_28 \
"Thy parents wish thee to become an\n\
apprentice. Two positions are available.\n\
Dost thou A) Become an acolyte in the\n\
Spiritual order, or B) Become an\n\
assistant to a humble village cobbler?"

#define U4TEXT_TITLE_1_TEXT_29 \
"  The day is warm, yet there is a\n\
cooling breeze.  The latest in a series\n\
of personal crises seems insurmountable.\n\
You are being pulled apart in all\n\
directions."

#define U4TEXT_TITLE_1_TEXT_30 \
"Yet this afternoon walk in the country-\n\
side slowly brings relaxation to your\n\
harried mind.  The soil and strain of\n\
modern high-tech living begins to wash\n\
off in layers. That willow tree near the\n\
stream looks comfortable and inviting."

#define U4TEXT_TITLE_1_TEXT_31 \
"The buzz of dragonflies and the whisper\n\
of the willow's swaying branches bring\n\
a deep peace.  Searching inward for\n\
tranquility and happiness, you close\n\
your eyes."

#define U4TEXT_TITLE_1_TEXT_32 \
"A high-pitched cascading sound like\n\
crystal wind-chimes impinges on your\n\
floating awareness.  As you open your\n\
eyes, you see a shimmering blueness rise\n\
from the ground.  The sound seems to be\n\
emanating from this glowing portal."

#define U4TEXT_TITLE_1_TEXT_33 \
"It is difficult to look at the blueness.\n\
Light seems to bend and distort around\n\
it, while the sound waves become so\n\
intense, they appear to become visible."

#define U4TEXT_TITLE_1_TEXT_34 \
"The portal hangs there for a moment;\n\
then, with the rush of an imploding\n\
vacuum, it sinks into the ground.\n\
Something remains suspended in mid-air\n\
for a moment before falling to earth\n\
with a heavy thud."

#define U4TEXT_TITLE_1_TEXT_35 \
"Somewhat shaken by this vision, you\n\
rise to your feet to investigate.  A\n\
crude circle of stones surrounds the\n\
spot where the portal appeared. There is\n\
something glinting in the grass."

#define U4TEXT_TITLE_1_TEXT_36 \
"You pick up an amulet shaped like a\n\
cross with a loop at the top.  It is an\n\
Ankh, the sacred symbol of life and\n\
rebirth.  But this could not have made\n\
the thud, so you look again and find\n\
a large book wrapped in thick cloth!"

#define U4TEXT_TITLE_1_TEXT_37 \
"With trembling hands you unwrap the\n\
book.  Behold, the cloth is a map, and\n\
within lies not one book, but two.  The\n\
map is of a land strange to you, and the\n\
style speaks of ancient cartography."

#define U4TEXT_TITLE_1_TEXT_38 \
"The script on the cover of the first\n\
book is arcane but readable.  The title\n\
is:\n\
        The History of Britannia\n\
               as told by\n\
            Kyle the Younger"

#define U4TEXT_TITLE_1_TEXT_39 \
"The other book is disturbing to look at.\n\
Its small cover appears to be fashioned\n\
out of some sort of leathery hide, but\n\
from what creature is uncertain.  The\n\
reddish-black skin radiates an intense\n\
aura suggestive of ancient power."

#define U4TEXT_TITLE_1_TEXT_40 \
"The tongue of the title is beyond your\n\
ken.  You dare not open the book and\n\
disturb whatever sleeps within.  You\n\
decide to peruse the History.  Settling\n\
back under the willow tree, you open the\n\
book."

#define U4TEXT_TITLE_1_TEXT_41 \
"\n\
\n\
    (You read the Book of History)"

#define U4TEXT_TITLE_1_TEXT_42 \
"\n\
\n\
(No, really! Read the Book of History!)"

#define U4TEXT_TITLE_1_TEXT_43 \
"Closing the book, you again pick up\n\
the Ankh.  As you hold it, you begin to\n\
hear a hauntingly familiar, lute-like\n\
sound wafting over a nearby hill.  Still\n\
clutching the strange artifacts, you\n\
rise unbidden and climb the slope."

#define U4TEXT_TITLE_1_TEXT_44 \
"In the valley below you see what appears\n\
to be a fair.  It seems strange that you\n\
came that way earlier and noticed\n\
nothing.  As you mull this over, your\n\
feet carry you down towards the site."

#define U4TEXT_TITLE_1_TEXT_45 \
"This is no ordinary travelling\n\
carnival, but a Renaissance Fair.  The\n\
pennants on the tent tops blow briskly\n\
in the late afternoon breeze."

#define U4TEXT_TITLE_1_TEXT_46 \
"The ticket taker at the RenFair's gate\n\
starts to ask you for money, but upon\n\
spotting your Ankh says, \"Welcome,\n\
friend.  Enter in peace and find your\n\
path.\""

#define U4TEXT_TITLE_1_TEXT_47 \
"The music continues to pull you\n\
forward amongst the merchants and\n\
vendors.  Glimpses of fabulous treasures\n\
can be seen in some of the shadowy\n\
booths."

#define U4TEXT_TITLE_1_TEXT_48 \
"These people are very happy.  They seem\n\
to glow with an inner light.  Some look\n\
up as you pass and smile, but you cannot\n\
stop - the music compels you to move\n\
onward through the crowd."

#define U4TEXT_TITLE_1_TEXT_49 \
"Through the gathering dusk you see a\n\
secluded gypsy wagon sitting off in the\n\
woods.  The music seems to emanate from\n\
the wagon.  As you draw near, a woman's\n\
voice weaves into the music, saying:\n\
\"You may approach, O seeker.\""

#define U4TEXT_TITLE_1_TEXT_50 \
"You enter to find an old gypsy sitting\n\
in a small curtained room.  She wears an\n\
Ankh around her neck. In front of her is\n\
a round table covered in deep green\n\
velvet.  The room smells so heavily of\n\
incense that you feel dizzy."

#define U4TEXT_TITLE_1_TEXT_51 \
"Seeing the Ankh, the ancient gypsy\n\
smiles and warns you never to part with\n\
it.  \"We have been waiting such a long\n\
time, but at last you have come.  Sit\n\
here and I shall read the path of your\n\
future.\""

#define U4TEXT_TITLE_1_TEXT_52 \
"Upon the table she places a curious\n\
wooden object like an abacus but without\n\
beads.  In her hands she holds eight\n\
unusual cards.  \"Let us begin the\n\
casting.\""

#define U4TEXT_TITLE_1_TEXT_53 "The gypsy places the first two cards\n"
#define U4TEXT_TITLE_1_TEXT_54 "The gypsy places two more of the cards\n"
#define U4TEXT_TITLE_1_TEXT_55 "The gypsy places the last two cards\n"
#define U4TEXT_TITLE_1_TEXT_56 "upon the table.  They are the cards of\n"

#define U4TEXT_TITLE_1_TEXT_57 "Honesty"
#define U4TEXT_TITLE_1_TEXT_58 "Compassion"
#define U4TEXT_TITLE_1_TEXT_59 "Valor"
#define U4TEXT_TITLE_1_TEXT_60 "Justice"
#define U4TEXT_TITLE_1_TEXT_61 "Sacrifice"
#define U4TEXT_TITLE_1_TEXT_62 "Honor"
#define U4TEXT_TITLE_1_TEXT_63 "Spirituality"
#define U4TEXT_TITLE_1_TEXT_64 "Humility"
#define U4TEXT_TITLE_1_TEXT_65 ""

#define U4TEXT_TITLE_1_TEXT_66 \
"With the final choice, the incense\n\
swells up around you.  The gypsy speaks\n\
as if from a great distance, her voice\n\
growing fainter with each word:\n\
\"So be it!  Thy path is chosen!\""

#define U4TEXT_TITLE_1_TEXT_67 \
"There is a moment of intense, wrenching\n\
vertigo.  As you open your eyes, a\n\
voice whispers within your mind, \"Seek\n\
the counsel of thy sovereign.\"  After a\n\
moment, the spinning subsides, and you\n\
open your eyes to..."

#define U4TEXT_TITLE_1_724 " and "
#define U4TEXT_TITLE_1_727 ".  She says\n\"Consider this:\""

#define U4TEXT_TITLE_1_820 "and"
#define U4TEXT_TITLE_1_823 "press drive letter"

#define U4TEXT_TITLE_1_847 "Insert PLAYER disk"
#define U4TEXT_TITLE_1_854 "Re-Insert PROGRAM disk"

#define U4TEXT_TITLE_1_864 "By what name shalt thou be known"
#define U4TEXT_TITLE_1_865 "in this world and time?"

#define U4TEXT_TITLE_1_875 "Art thou Male or Female? "

#endif
