@echo off
set OLDPATH=%PATH%
set PATH=%PATH%;%MSC4%;C:\MASM611\BIN

\TOOLS\MASM611 /z /Zd /w2 /v VGA_DRV.ASM;
pause
\TOOLS\LINK300 VGA_DRV.OBJ;
\TOOLS\exe2bin VGA_DRV.EXE EGA2.DRV

set PATH=%OLDPATH%
set OLDPATH=
