\TOOLS\MASM510 CGA_DRV.ASM;
\TOOLS\LINK240 CGA_DRV.OBJ;
\TOOLS\exe2bin CGA_DRV.EXE CGA.DRV
fc /b CGA.DRV ..\ORIGINAL\CGA.DRV

\TOOLS\MASM611 /z /Zd /w2 /v EGA_DRV.ASM;
pause
\TOOLS\LINK300 EGA_DRV.OBJ;
\TOOLS\exe2bin EGA_DRV.EXE EGA2.DRV
fc /b EGA2.DRV ..\ORIGINAL\EGA.DRV
