/*
 * Ultima IV - Quest Of The Avatar
 * (c) Copyright 1987 Lord British
 */

#ifndef __U4_I18N_H__
#define __U4_I18N_H__

/* U4_UTIL.C */
#define U4TEXT_UTIL_PASS "Pass\n"
#define U4TEXT_UTIL_78 "\n Thou hast lost\n  an Eighth!\n"
#define U4TEXT_UTIL_365 " SHP:"
#define U4TEXT_UTIL_368 " G:"

#define U4TEXT_UTIL_426 "\n\n\nAll is Dark...\n"
#define U4TEXT_UTIL_428 "\nBut wait...\n"
#define U4TEXT_UTIL_430 "Where am I?...\n"
#define U4TEXT_UTIL_432 "Am I dead?...\n"
#define U4TEXT_UTIL_434 "Afterlife?...\n"
#define U4TEXT_UTIL_436 "You hear:\n"
#define U4TEXT_UTIL_441 "I feel motion...\n"

#define U4TEXT_UTIL_474 "\n\nLord British says: I have pulled thy spirit and some possessions from the void.  Be more careful in the future!\n"

#define U4TEXT_UTIL_533 "What?\n"
#define U4TEXT_UTIL_539 "Can't!\n"
#define U4TEXT_UTIL_545 "Not Here!\n"
#define U4TEXT_UTIL_551 "Disabled!\n"
#define U4TEXT_UTIL_557 "Only on foot!\n"
#define U4TEXT_UTIL_563 "Slow progress!\n"
#define U4TEXT_UTIL_568 "None left!\n"

#define U4TEXT_UTIL_NORTH "North"
#define U4TEXT_UTIL_SOUTH "South"
#define U4TEXT_UTIL_EAST "East"
#define U4TEXT_UTIL_WEST "West"

#define U4TEXT_UTIL_802 "Thy Ship Sinks!\n"

#endif
