/*
 * Ultima IV - Quest Of The Avatar
 * (c) Copyright 1987 Lord British
 */

#ifndef __U4_I18N_EN_H__
#define __U4_I18N_EN_H__

/* U4_COMBA.C */
#define U4TEXT_COMBA_76 " with "
#define U4TEXT_COMBA_128 "Bad command\n"
#define U4TEXT_COMBA_183 "Killed!\n"
#define U4TEXT_COMBA_189 "Exp. "
#define U4TEXT_COMBA_202 "Fleeing!\n"
#define U4TEXT_COMBA_204 "Critical!\n"
#define U4TEXT_COMBA_208 "Heavily "
#define U4TEXT_COMBA_210 "Lightly "
#define U4TEXT_COMBA_212 "Barely "
#define U4TEXT_COMBA_214 "Wounded!\n"
#define U4TEXT_COMBA_267 "Missed!\n"
#define U4TEXT_COMBA_331 "Last one!\n"
#define U4TEXT_COMBA_409 "Attack\n"
#define U4TEXT_COMBA_423 "Nothing to Attack!\n"


/* U4_COMBB.C */
#define U4TEXT_COMBB_91 "All must use same exit!\n"
#define U4TEXT_COMBB_203 "North\n"
#define U4TEXT_COMBB_210 "South\n"
#define U4TEXT_COMBB_217 "East\n"
#define U4TEXT_COMBB_224 "West\n"

/* U4_COMBC.C */
#define U4TEXT_COMBC_321 "\n\n**** Combat ****\n\n"
#define U4TEXT_COMBC_438 "\nThe Altar Room of "
#define U4TEXT_COMBC_440 "Love\n"
#define U4TEXT_COMBC_443 "Truth\n"
#define U4TEXT_COMBC_446 "Courage\n"
#define U4TEXT_COMBC_592 "Battle is lost!\n"
#define U4TEXT_COMBC_599 "Leave Room!\n"
#define U4TEXT_COMBC_615 "into Dungeon\n"
#define U4TEXT_COMBC_628 "\nVictory!\n"

/* U4_EXPLO.C */
#define U4TEXT_EXPLO_126 "Enter "

/* U4_MAP.C*/
#define U4TEXT_MAP_109 "Leaving...\n"
#define U4TEXT_MAP_258 "Blocked!\n"
#define U4TEXT_MAP_265 "Drift Only!\n"
#define U4TEXT_MAP_359 "Turn North!\n"
#define U4TEXT_MAP_361 "Sail North!\n"
#define U4TEXT_MAP_373 "North\n"
#define U4TEXT_MAP_415 "Turn South!\n"
#define U4TEXT_MAP_417 "Sail South!\n"
#define U4TEXT_MAP_427 "South\n"
#define U4TEXT_MAP_474 "Turn West!\n"
#define U4TEXT_MAP_476 "Sail West!\n"
#define U4TEXT_MAP_488 "West\n"
#define U4TEXT_MAP_533 "Turn East!\n"
#define U4TEXT_MAP_535 "Sail East!\n"
#define U4TEXT_MAP_549 "East\n"

/* U4_UTIL.C */
#define U4TEXT_UTIL_PASS "Pass\n"
#define U4TEXT_UTIL_78 "\n Thou hast lost\n  an Eighth!\n"
#define U4TEXT_UTIL_365 " SHP:"
#define U4TEXT_UTIL_368 " G:"

#define U4TEXT_UTIL_426 "\n\n\nAll is Dark...\n"
#define U4TEXT_UTIL_428 "\nBut wait...\n"
#define U4TEXT_UTIL_430 "Where am I?...\n"
#define U4TEXT_UTIL_432 "Am I dead?...\n"
#define U4TEXT_UTIL_434 "Afterlife?...\n"
#define U4TEXT_UTIL_436 "You hear:\n"
#define U4TEXT_UTIL_441 "I feel motion...\n"

#define U4TEXT_UTIL_474 "\n\nLord British says: I have pulled thy spirit and some possessions from the void.  Be more careful in the future!\n"

#define U4TEXT_UTIL_533 "What?\n"
#define U4TEXT_UTIL_539 "Can't!\n"
#define U4TEXT_UTIL_545 "Not Here!\n"
#define U4TEXT_UTIL_551 "Disabled!\n"
#define U4TEXT_UTIL_557 "Only on foot!\n"
#define U4TEXT_UTIL_563 "Slow progress!\n"
#define U4TEXT_UTIL_568 "None left!\n"

#define U4TEXT_UTIL_NORTH "North"
#define U4TEXT_UTIL_SOUTH "South"
#define U4TEXT_UTIL_EAST "East"
#define U4TEXT_UTIL_WEST "West"

#define U4TEXT_UTIL_802 "Thy Ship Sinks!\n"

#endif
